import { ref, computed, onMounted } from 'vue'

export type Locale = 'en' | 'fr' | 'ar'

const currentLocale = ref<Locale>('en')

const translations = {
    en: {
        nav: {
            catalog: 'Collections',
            packages: 'Packages',
            boutique: 'Boutique',
            about: 'The Maison',
            contact: 'Concierge',
            login: 'Login',
            admin_portal: 'Workshop Overview',
            orders: 'Treasure History',
            products: 'Creations',
            categories: 'Curations',
            brands: 'Artisans',
            stores: 'Boutiques',
            pos: 'Terminal',
            dashboard: 'Maison Analytics',
            users: 'Users',
            settings: 'Settings'
        },
        footer: {
            luxury: 'Luxury Gold & Jewelry',
            tagline: 'Timeless Elegance from Dubai',
            client_care: 'Client Care',
            book_appt: 'Book Appt.',
            heritage: 'Heritage',
            rights: 'All Rights Reserved.',
            collections: 'Collections',
            all_jewelry: 'All Jewelry',
            gold_rings: 'Gold Rings',
            diamond_necklaces: 'Diamond Necklaces',
            luxury_watches: 'Luxury Watches',
            bridal_set: 'Bridal Set',
            maison: 'The Maison',
            careers: 'Careers',
            shipping_returns: 'Shipping & Returns',
            size_guide: 'Size Guide',
            jewelry_care: 'Jewelry Care'
        },
        common: {
            search: 'Search products...',
            search_btn: 'Search',
            cart: 'Cart',
            language: 'Language',
            back_to_store: 'Back to Store',
            logout: 'Logout',
            welcome: 'Welcome back',
            explore: 'Explore Collection',
            visit: 'Visit Boutique',
            currency: 'MAD',
            email: 'Email',
            phone: 'Phone',
            total: 'Total',
            left: 'left',
            try_again: 'Try Again',
            go_home: 'Go Home',
            error_title: 'Something went wrong',
            error_desc: 'We encountered an error while loading this content.',
            admin: 'Admin',
            page_not_found: 'Page Not Found',
            page_not_found_desc: 'The masterpiece you are looking for has been moved or does not exist in this collection.',
            report_issue: 'Report Issue',
            top_rated: 'Top Rated'
        },
        cart: {
            title: 'Shopping Cart',
            empty: 'Your cart is empty',
            checkout: 'Checkout',
            shipping_hint: 'Shipping & taxes calculated at checkout'
        },
        admin: {
            dashboard: 'Maison Analytics',
            welcome_back: 'Welcome to the Atelier,',
            total_revenue: 'Heritage Value',
            recent_products: 'Latest Masterpieces',
            manage_admins: 'Manage Admins',
            add_product: 'Archive New Creation',
            products: 'Creations',
            loading_data: 'Loading data...',
            failed_load: 'Failed to load data',
            retry: 'Retry',
            no_products: 'No products to display',
            product: 'Creation',
            brand: 'Artisan',
            price: 'Price',
            stock: 'Stock',
            rating: 'Rating',
            actions: 'Actions',
            search_placeholder: 'Search products...',
            delete_confirm: "Are you sure you want to delete '{name}'? This action cannot be undone.",
            delete: 'Delete',
            edit: 'Edit',
            cancel: 'Cancel',
            save_success: 'Saved successfully',
            delete_success: 'Deleted successfully',
            save_failed: 'Failed to save',
            low_stock_alerts: 'Low Stock Alerts',
            name: 'Name',
            description: 'Description',
            select_category: 'Select Category',
            select_brand: 'Select Brand',
            image: 'Product Image',
            image_url: 'External URL',
            upload_image: 'Upload Image',
            uploading: 'Uploading...',
            update_product: 'Update Product',
            brands_management: 'Brand Management',
            categories_management: 'Category Management',
            stores_management: 'Store Management',
            add_brand: 'Add Brand',
            add_category: 'Add Category',
            add_store: 'Add Store',
            logo_url: 'Logo URL',
            address: 'Address',
            city: 'City',
            phone: 'Phone',
            orders_management: 'Order Management',
            order_id: 'Order ID',
            date: 'Date',
            items: 'Items',
            status: 'Status',
            completed: 'Completed',
            pending: 'Pending',
            average_value: 'Avg. Order Value',
            export_csv: 'Export CSV',
            users_management: 'User Management',
            username: 'Username',
            email: 'Email',
            phone_number: 'Phone Number',
            role: 'Role',
            active: 'Active',
            inactive: 'Inactive',
            super_admin: 'Super Admin',
            admin: 'Admin',
            first_name: 'First Name',
            last_name: 'Last Name',
            password: 'Password',
            set_as_super_admin: 'Set as Super Admin',
            store_info: 'Store Information',
            home_page_content: 'Home Page Content',
            theme_customization: 'Theme Customization',
            primary_color: 'Primary Color',
            secondary_color: 'Secondary Color',
            accent_color: 'Accent Color',
            main_font: 'Main Font',
            default: 'Default',
            save_changes: 'Save Changes',
            hero_title_label: 'Hero Title (HTML allowed)',
            hero_subtitle_label: 'Hero Subtitle',
            hero_badge_label: 'Hero Badge',
            saving: 'Saving...',
            admin_login: 'Admin Login',
            backend_online: 'Backend Online',
            backend_offline: 'Backend Offline',
            confirm_dialog: {
                default_title: 'Are you sure?',
                default_message: 'This action cannot be undone.',
                confirm: 'Confirm',
                cancel: 'Cancel'
            },
            checking_connectivity: 'Checking Connectivity...',
            sign_in_subtitle: 'Sign in to access the admin dashboard',
            forgot_password: 'Forgot Password?',
            signing_in: 'Signing in...',
            sign_in: 'Sign In',
            invalid_credentials: 'Invalid username or password',
            weekly_sales: 'Weekly Sales',
            healthy_stock: 'All stocks are healthy! ✅',
            sales: 'Sales',
            dashboard_overview: 'Dashboard Overview',
            customer: 'Customer',
            guest: 'Guest',
            payment: 'Payment',
            view_details: 'View Details',
            print_receipt: 'Print Receipt',
            add_admin: 'Add Admin',
            quick_actions: 'Quick Actions',
            edit_categories: 'Edit Categories',
            edit_brands: 'Edit Brands'
        },
        pos: {
            title: 'Artisan Terminal',
            back_to_admin: 'Back to Admin',
            current_order: 'Current Order',
            clear_all: 'Clear All',
            cart_empty: 'Cart is empty',
            add_hint: 'Click products to add them',
            subtotal: 'Subtotal',
            tax: 'Tax',
            total: 'Total',
            processing: 'Processing...',
            order_placed: 'Order Placed!',
            complete_order: 'Complete Order',
            order_error: 'Error placing order'
        },
        about: {
            title: 'About Us',
            hero_title: 'The Art of Timeless Luxury',
            hero_subtitle: 'Your premier destination for exclusive jewelry and exquisite gold creations.',
            mission_title: 'Our Mission',
            mission_desc: 'We believe jewelry should be more than just an ornament—it should be a legacy. At Maison El Wali, we bridge the gap between signature design and artisanal mastery.',
            premium_brands: 'Premium Brands',
            global_showrooms: 'Global Showrooms',
            expert_support: 'Expert Support',
            why_choose_us: 'Why Choose Us',
            standards_desc: 'The standards that define our collection',
            curated_excellence: 'Curated Excellence',
            curated_desc: 'Every piece is hand-picked for superior craftsmanship, design, and eternal value.',
            innovation_first: 'Artisan Heritage',
            innovation_desc: 'Access exclusive high-jewelry collections handcrafted by our master goldsmiths.',
            premium_guarantee: 'Premium Guarantee',
            guarantee_desc: 'Comprehensive warranty coverage and dedicated concierge support for every purchase.',
            ready_to_experience: 'Ready to Experience It?',
            cta_desc: 'Visit our digital showroom or find a location near you.',
            browse_collection: 'Browse Collection',
            find_store: 'Find a Store'
        },
        home: {
            title: 'Home',
            meta_desc: 'Maison El Wali - The pinnacle of luxury gold and jewelry. Discover our exclusive collections.',
            luxury_authentic: 'Authentic Luxury',
            luxury_desc: 'Every piece is certified and crafted with the highest purity gold.',
            global_shipping: 'Global Shipping',
            shipping_desc: 'Secure, insured delivery to your doorstep, anywhere in the world.',
            bespoke_design: 'Bespoke Design',
            bespoke_desc: 'Collaborate with our artisans to bring your unique vision to life.',
            gold_standard: 'The Gold Standard',
            teaser_desc: 'From Dubai to the world, we bring you jewelry that transcends generations.',
            read_story: 'Read Our Story'
        },
        catalog: {
            title: 'Product Catalog',
            quick_actions: 'Quick Actions',
            edit_categories: 'Edit Categories',
            edit_brands: 'Edit Brands',
            loading: 'Loading products...',
            failed: 'Failed to load products',
            error_desc: 'We couldn\'t load the product catalog. Please check your connection and try again.',
            filters: 'Filters',
            clear_all: 'Clear All',
            categories: 'Categories',
            brands: 'Brands',
            search_placeholder: 'Search products...',
            count_plural: 'products',
            sort_featured: 'Featured',
            sort_price_low: 'Price: Low to High',
            sort_price_high: 'Price: High to Low',
            sort_rating: 'Highest Rated',
            no_found: 'No products found',
            no_found_desc: 'Try adjusting your search or filters'
        },
        boutique: {
            title: 'Flagship Boutique',
            meta_desc: 'Visit our flagship boutique in Dubai. Experience luxury service and exclusive jewelry collections.',
            experience: 'The Experience',
            hero_title: 'Our Flagship Boutique',
            hero_subtitle: 'Immerse yourself in a world of refined luxury at our Dubai showroom.',
            visit_us: 'Visit Us',
            get_directions: 'Get Directions',
            call: 'Call Boutique',
            hours: 'Opening Hours',
            mon_fri: 'Mon - Fri',
            sat_sun: 'Sat - Sun',
            appointments: 'Private Appointments',
            appointments_desc: 'For a personalized experience, book a private viewing with our senior jewelry consultants.',
            book: 'Book an Appointment',
            map_view: 'Map View',
            services: 'Boutique Services',
            custom_design: 'Custom Design',
            custom_desc: 'Work with our artisans to create a one-of-a-kind piece.',
            spa: 'Jewelry Spa',
            spa_desc: 'Professional cleaning and restoration for your precious items.',
            vip: 'VIP Lounge',
            vip_desc: 'Enjoy refreshments in our private viewing suites.'
        },
        contact: {
            title: 'Contact Us',
            meta_desc: 'Get in touch with Maison El Wali. Visit our showrooms, call our support line, or send us a message.',
            support: 'SUPPORT',
            hero_title_1: 'Get in',
            hero_title_2: 'Touch',
            hero_subtitle: 'Our concierge team is at your service for every inquiry.',
            visit_flagship: 'Visit Our Flagship',
            call_support: 'Call Support',
            email_us: 'Email Us',
            message_received: 'Message Received',
            thanks: 'Thank you for contacting Maison El Wali. Our concierge team has received your inquiry and will respond shortly.',
            send_another: 'Send Another Message',
            send_message: 'Send a Message',
            name: 'Name',
            subject: 'Subject',
            topic_placeholder: 'Select a topic',
            topic_support: 'Jewelry Maintenance',
            topic_partnership: 'Partnership',
            topic_other: 'Other',
            message: 'Message',
            message_placeholder: 'How can we help you today?',
            sending: 'Sending...',
            send_btn: 'Send Message',
            hq_name: 'Maison El Wali HQ',
            hq_address: 'Marrakesh, Morocco'
        },
        packages: {
            title: 'Exclusive Packages',
            meta_desc: 'Curated jewelry packages and gift sets for special occasions.',
            hero_title: 'Curated Packages',
            hero_subtitle: 'Exclusive sets designed for your most cherished moments',
            view_details: 'View Details',
            custom_title: 'Custom Packages',
            custom_desc: 'Looking for something unique? Our stylists can provide a consultation.',
            request: 'Request Consultation',
            pkg1_name: 'Bridal Elegance Set',
            pkg1_desc: 'Complete wedding day jewelry set tailored for the modern bride. Includes necklace, earrings, and bracelet.',
            pkg2_name: 'Anniversary Collection',
            pkg2_desc: 'Celebrate your milestone with our hand-picked anniversary favorites. A timeless ring and matching pendant.',
            pkg3_name: 'Everyday Luxury',
            pkg3_desc: 'Subtle yet stunning pieces designed for daily wear. Elevate your everyday style.',
            pkg4_name: 'Royal Gemstone Suite',
            pkg4_desc: 'A majestic collection featuring sapphire and diamond accents. Fit for royalty.'
        }
        ,
        wishlist: {
            title: 'Wishlist',
            empty_title: 'Wishlist is empty',
            empty_desc: 'You haven\'t added any treasures to your collection yet.',
            browse: 'Browse Products',
            added_success: 'Added to your wishlist.',
            removed_success: 'Removed from your wishlist.',
            add_failed: 'Failed to add to wishlist.',
            remove_failed: 'Failed to remove from wishlist.'
        },
        account: {
            welcome: 'Welcome,',
            dashboard_desc: 'Manage your heritage collection and treasures.',
            total_orders: 'Total Acquisitions',
            recent_orders: 'Recent Heritage',
            view_all: 'View All History',
            no_orders: 'No orders yet.',
            order_history: 'Order History',
            loading: 'Loading...',
            order_id: 'Order ID',
            date: 'Date',
            status: 'Status',
            total: 'Total',
            no_previous_orders: 'No previous orders.',
            shop_now: 'Shop Now',
            account_settings: 'Account Settings',
            first_name: 'First Name',
            last_name: 'Last Name',
            save_success: 'Profile updated successfully',
            save_failed: 'Update failed',
            saving: 'Saving...',
            save_changes: 'Save Changes',
            logout: 'Logout'
        },
        checkout: {
            title: 'Checkout',
            contact_info: 'Contact Information',
            shipping_address: 'Shipping Address',
            payment_method: 'Payment Method',
            email_label: 'Email Address',
            email_placeholder: 'you@email.com',
            first_name: 'First Name',
            last_name: 'Last Name',
            address: 'Address',
            address_placeholder: '123 Main St',
            city: 'City',
            country: 'Country',
            zip: 'ZIP / Postal',
            cod_title: 'Cash on Delivery',
            cod_desc: 'Pay in cash when you receive your order',
            place_order: 'Place Order',
            processing: 'Processing...',
            pay: 'Pay',
            order_summary: 'Order Summary',
            shipping: 'Shipping',
            free: 'Free',
            tax: 'Tax',
            total: 'Total',
            email_error: 'Valid email required',
            required_error: 'Required',
            failed_order: 'Failed to place order. Please try again.'
        },
        confirmation: {
            title: 'Order Confirmed!',
            subtitle: 'Thank you for your purchase.',
            order_id: 'Order ID',
            message: 'We\'ve sent a confirmation email to your inbox. You can track your order status in your account.',
            continue_shopping: 'Continue Shopping',
            back_home: 'Back to Home'
        },
        search: {
            title: 'Search Results',
            results_for: 'results for',
            placeholder: 'Search products, brands, categories...',
            no_found: 'No products found',
            no_found_q: 'Try different keywords or browse our catalog',
            no_found_no_q: 'Enter a search term to find products',
            browse: 'Browse Catalog'
        },
        pdp: {
            details: 'Product Details',
            loading: 'Loading product details...',
            not_found: 'Product Not Found',
            not_found_desc: 'The product you are looking for does not exist or could not be loaded.',
            home: 'Home',
            catalog: 'Catalog',
            reviews: 'reviews',
            in_stock: 'In Stock',
            out_stock: 'Out of Stock',
            add_to_cart: 'Add to Cart',
            quantity: 'Quantity',
            added_to_cart: 'has been added to your cart.',
            specs: 'Specifications',
            related: 'You Might Also Like',
            quick_view: 'Quick View',
            add_wishlist: 'Add to Wishlist',
            view: 'View'
        },
        stores: {
            title: 'Our Locations',
            meta_desc: 'Find a showroom near you. Experience our products in person.',
            hero_title: 'Find Your Nearest Store',
            hero_subtitle: 'Experience our products in person at one of our premium showrooms',
            locations: 'Locations',
            get_directions: 'Get Directions',
            call: 'Call Store',
            map_title: 'Interactive Map',
            map_desc: 'Connect Google Maps API to display locations',
            hours: 'Store Hours',
            mon_sat: 'Mon-Sat',
            sun: 'Sun',
            expert_staff: 'Expert Staff',
            expert_desc: 'Our trained specialists will help you find the perfect creation',
            service_center: 'Artisan Workshop',
            service_desc: 'In-store resizing and professional maintenance available',
            experience_person: 'Experience it in Person',
            experience_desc: 'Visit one of our premium showrooms to try this piece before you buy.'
        }
    },
    fr: {
        nav: {
            catalog: 'Collections',
            packages: 'Forfaits',
            boutique: 'Boutique',
            about: 'La Maison',
            contact: 'Conciergerie',
            login: 'Connexion',
            admin_portal: "Aperçu de l'Atelier",
            orders: 'Historique des Trésors',
            products: 'Créations',
            categories: 'Curations',
            brands: 'Artisans',
            stores: 'Boutiques',
            pos: 'Terminal',
            dashboard: 'Analytiques de la Maison',
            users: 'Utilisateurs',
            settings: 'Paramètres'
        },
        footer: {
            luxury: 'Or et Bijoux de Luxe',
            tagline: "L'élégance intemporelle de Dubaï",
            client_care: 'Service Client',
            book_appt: 'Rendez-vous',
            heritage: 'Héritage',
            rights: 'Tous droits réservés.',
            collections: 'Collections',
            all_jewelry: 'Tous les bijoux',
            gold_rings: 'Bagues en or',
            diamond_necklaces: 'Colliers en diamant',
            luxury_watches: 'Montres de luxe',
            bridal_set: 'Ensemble de mariage',
            maison: 'La Maison',
            careers: 'Carrières',
            shipping_returns: 'Livraison & Retours',
            size_guide: 'Guide des tailles',
            jewelry_care: 'Entretien des bijoux'
        },
        common: {
            search: 'Rechercher des produits...',
            search_btn: 'Rechercher',
            cart: 'Panier',
            language: 'Langue',
            back_to_store: 'Retour à la boutique',
            logout: 'Déconnexion',
            welcome: 'Bon retour',
            explore: 'Explorer la Collection',
            visit: 'Visiter la Boutique',
            currency: 'MAD',
            email: 'E-mail',
            phone: 'Téléphone',
            total: 'Total',
            left: 'restant',
            try_again: 'Réessayer',
            go_home: 'Accueil',
            error_title: 'Quelque chose s\'est mal passé',
            error_desc: 'Nous avons rencontré une erreur lors du chargement de ce contenu.',
            admin: 'Administrateur',
            page_not_found: 'Page Non Trouvée',
            page_not_found_desc: 'Le chef-d\'œuvre que vous recherchez a été déplacé ou n\'existe pas dans cette collection.',
            report_issue: 'Signaler un Problème',
            top_rated: 'Mieux Noté'
        },
        cart: {
            title: 'Panier d\'achat',
            empty: 'Votre panier est vide',
            checkout: 'Paiement',
            shipping_hint: 'Frais de port et taxes calculés au paiement'
        },
        admin: {
            dashboard: 'Analytiques de la Maison',
            welcome_back: "Bienvenue à l'Atelier,",
            total_revenue: 'Valeur du Patrimoine',
            recent_products: "Derniers Chefs-d'œuvre",
            manage_admins: 'Gérer les admins',
            add_product: 'Archiver une Création',
            products: 'Créations',
            loading_data: 'Chargement des données...',
            failed_load: 'Échec du chargement',
            retry: 'Réessayer',
            no_products: 'Aucun produit à afficher',
            product: 'Création',
            brand: 'Artisan',
            price: 'Prix',
            stock: 'Stock',
            rating: 'Note',
            actions: 'Actions',
            search_placeholder: 'Rechercher...',
            delete_confirm: "Êtes-vous sûr de vouloir supprimer '{name}' ?",
            delete: 'Supprimer',
            edit: 'Modifier',
            cancel: 'Annuler',
            save_success: 'Enregistré avec succès',
            delete_success: 'Supprimé avec succès',
            save_failed: "Échec de l'enregistrement",
            low_stock_alerts: 'Alertes stock faible',
            name: 'Nom',
            description: 'Description',
            select_category: 'Choisir la catégorie',
            select_brand: 'Choisir la marque',
            image: 'Image du produit',
            image_url: 'Lien externe',
            upload_image: 'Télécharger',
            uploading: 'Téléchargement...',
            update_product: 'Mettre à jour',
            brands_management: 'Gestion des marques',
            categories_management: 'Gestion des catégories',
            stores_management: 'Gestion des magasins',
            add_brand: 'Ajouter une marque',
            add_category: 'Ajouter une catégorie',
            add_store: 'Ajouter un magasin',
            logo_url: 'Lien du logo',
            address: 'Adresse',
            city: 'Ville',
            phone: 'Téléphone',
            orders_management: 'Gestion des commandes',
            order_id: 'ID Commande',
            date: 'Date',
            items: 'Articles',
            status: 'Statut',
            completed: 'Terminé',
            pending: 'En attente',
            average_value: 'Valeur moyenne',
            export_csv: 'Exporter CSV',
            users_management: 'Gestion des utilisateurs',
            username: "Nom d'utilisateur",
            email: 'E-mail',
            phone_number: 'Numéro de téléphone',
            role: 'Rôle',
            active: 'Actif',
            inactive: 'Inactif',
            super_admin: 'Super Admin',
            admin: 'Admin',
            first_name: 'Prénom',
            last_name: 'Nom',
            password: 'Mot de passe',
            set_as_super_admin: 'Définir comme Super Admin',
            store_info: 'Informations du magasin',
            home_page_content: "Contenu de la page d'accueil",
            theme_customization: 'Personnalisation du thème',
            primary_color: 'Couleur primaire',
            secondary_color: 'Couleur secondaire',
            accent_color: 'Couleur accentuée',
            main_font: 'Police principale',
            default: 'Par défaut',
            save_changes: 'Enregistrer les modifications',
            hero_title_label: 'Titre principal (HTML autorisé)',
            hero_subtitle_label: 'Sous-titre',
            hero_badge_label: 'Badge du bandeau',
            saving: 'Enregistrement...',
            admin_login: 'Connexion Admin',
            backend_online: 'Serveur en ligne',
            backend_offline: 'Serveur hors ligne',
            confirm_dialog: {
                default_title: 'Êtes-vous sûr ?',
                default_message: 'Cette action ne peut pas être annulée.',
                confirm: 'Confirmer',
                cancel: 'Annuler'
            },
            checking_connectivity: 'Vérification de la connexion...',
            sign_in_subtitle: 'Connectez-vous pour accéder au tableau de bord',
            forgot_password: 'Mot de passe oublié ?',
            signing_in: 'Connexion...',
            sign_in: 'Se connecter',
            invalid_credentials: "Nom d'utilisateur ou mot de passe invalide",
            weekly_sales: 'Ventes hebdomadaires',
            healthy_stock: 'Tous les stocks sont sains ! ✅',
            sales: 'Ventes',
            dashboard_overview: 'Aperçu du tableau de bord',
            customer: 'Client',
            guest: 'Invité',
            payment: 'Paiement',
            view_details: 'Voir les détails',
            print_receipt: 'Imprimer le reçu',
            add_admin: 'Ajouter un administrateur',
            quick_actions: 'Actions Rapides',
            edit_categories: 'Gérer les catégories',
            edit_brands: 'Gérer les marques'
        },
        wishlist: {
            title: 'Liste de souhaits',
            empty_title: 'Liste de souhaits vide',
            empty_desc: 'Vous n\'avez pas encore ajouté de trésors à votre collection.',
            browse: 'Parcourir les produits',
            added_success: 'Ajouté à votre liste de souhaits.',
            removed_success: 'Retiré de votre liste de souhaits.',
            add_failed: 'Échec de l\'ajout à la liste.',
            remove_failed: 'Échec de la suppression de la liste.'
        },
        account: {
            welcome: 'Bienvenue,',
            dashboard_desc: 'Gérez votre collection patrimoniale et vos trésors.',
            total_orders: 'Acquisitions Totales',
            recent_orders: 'Patrimoine Récent',
            view_all: 'Héritage Complet',
            no_orders: 'Pas encore de commandes.',
            order_history: 'Historique des commandes',
            loading: 'Chargement...',
            order_id: 'ID Commande',
            date: 'Date',
            status: 'Statut',
            total: 'Total',
            no_previous_orders: 'Pas de commandes précédentes.',
            shop_now: 'Achetez maintenant',
            account_settings: 'Paramètres du compte',
            first_name: 'Prénom',
            last_name: 'Nom de famille',
            save_success: 'Profil mis à jour avec succès',
            save_failed: 'Échec de la mise à jour',
            saving: 'Enregistrement...',
            save_changes: 'Enregistrer les modifications',
            my_account: 'Mon compte',
            logout: 'Déconnexion'
        },
        pos: {
            title: 'Terminal Artisan',
            back_to_admin: "Retour à l'admin",
            current_order: 'Commande actuelle',
            clear_all: 'Tout effacer',
            cart_empty: 'Le panier est vide',
            add_hint: 'Cliquez sur les produits pour les ajouter',
            subtotal: 'Sous-total',
            tax: 'Taxe',
            total: 'Total',
            processing: 'Traitement...',
            order_placed: 'Commande passée !',
            complete_order: 'Finaliser la commande',
            order_error: 'Erreur lors de la commande'
        },
        about: {
            title: 'À propos de nous',
            hero_title: 'L\'Art du Luxe Éternel',
            hero_subtitle: 'Votre destination privilégiée pour des bijoux exclusifs et des créations en or exquis.',
            mission_title: 'Notre mission',
            mission_desc: 'Nous pensons que les bijoux doivent être plus qu\'un simple ornement - ils doivent être un héritage. Chez Maison El Wali, nous comblons le fossé entre le design signature et la maîtrise artisanale.',
            premium_brands: 'Marques haut de gamme',
            global_showrooms: 'Showrooms mondiaux',
            expert_support: 'Assistance expert',
            why_choose_us: 'Pourquoi nous choisir',
            standards_desc: 'Les standards qui définissent notre collection',
            curated_excellence: 'Excellence sélectionnée',
            curated_desc: 'Chaque pièce est choisie avec soin pour son artisanat supérieur, son design et sa valeur éternelle.',
            innovation_first: 'Héritage Artisanal',
            innovation_desc: "Accédez à des collections exclusives de haute joaillerie fabriquées à la main par nos maîtres orfèvres.",
            premium_guarantee: 'Garantie Premium',
            guarantee_desc: "Couverture de garantie complète et assistance concierge dédiée pour chaque achat.",
            ready_to_experience: 'Prêt à vivre l\'expérience ?',
            cta_desc: 'Visitez notre showroom numérique ou trouvez un point de vente près de chez vous.',
            browse_collection: 'Parcourir la collection',
            find_store: 'Trouver un magasin'
        },
        home: {
            title: 'Accueil',
            meta_desc: 'Maison El Wali - Le summum de l\'or et de la joaillerie de luxe. Découvrez nos collections exclusives.',
            luxury_authentic: 'Luxe Authentique',
            luxury_desc: 'Chaque pièce est certifiée et fabriquée avec l\'or le plus pur.',
            global_shipping: 'Livraison Mondiale',
            shipping_desc: 'Livraison sécurisée et assurée à votre porte, partout dans le monde.',
            bespoke_design: 'Design Sur Mesure',
            bespoke_desc: 'Collaborez avec nos artisans pour donner vie à votre vision unique.',
            gold_standard: 'Le Standard d\'Or',
            teaser_desc: 'De Dubaï au monde entier, nous vous apportons des bijoux qui transcendent les générations.',
            read_story: 'Lire Notre Histoire'
        },
        catalog: {
            title: 'Catalogue de Produits',
            quick_actions: 'Actions Rapides',
            edit_categories: 'Modifier les Catégories',
            edit_brands: 'Modifier les Marques',
            loading: 'Chargement des produits...',
            failed: 'Échec du chargement des produits',
            error_desc: 'Nous n\'avons pas pu charger le catalogue. Veuillez vérifier votre connexion et réessayer.',
            filters: 'Filtres',
            clear_all: 'Tout effacer',
            categories: 'Catégories',
            brands: 'Marques',
            search_placeholder: 'Rechercher des produits...',
            count_plural: 'produits',
            sort_featured: 'En vedette',
            sort_price_low: 'Prix : Croissant',
            sort_price_high: 'Prix : Décroissant',
            sort_rating: 'Mieux notés',
            no_found: 'Aucun produit trouvé',
            no_found_desc: 'Essayez d\'ajuster votre recherche ou vos filtres'
        },
        boutique: {
            title: 'Boutique Phare',
            meta_desc: 'Visitez notre boutique phare à Dubaï. Découvrez un service de luxe et des collections de bijoux exclusives.',
            experience: 'L\'Expérience',
            hero_title: 'Notre Boutique Phare',
            hero_subtitle: 'Plongez dans un monde de luxe raffiné dans notre showroom de Dubaï.',
            visit_us: 'Visitez-nous',
            get_directions: 'Obtenir l\'itinéraire',
            call: 'Appeler la Boutique',
            hours: 'Heures d\'Ouverture',
            mon_fri: 'Lun - Ven',
            sat_sun: 'Sam - Dim',
            appointments: 'Rendez-vous Privés',
            appointments_desc: 'Pour une expérience personnalisée, réservez une visite privée avec nos conseillers experts.',
            book: 'Prendre Rendez-vous',
            map_view: 'Vue Carte',
            services: 'Services Boutique',
            custom_design: 'Design Personnalisé',
            custom_desc: 'Travaillez avec nos artisans pour créer une pièce unique.',
            spa: 'Spa Bijoux',
            spa_desc: 'Nettoyage professionnel et restauration de vos articles précieux.',
            vip: 'Salon VIP',
            vip_desc: 'Profitez de rafraîchissements dans nos suites de visionnage privées.'
        },
        contact: {
            title: 'Contactez-nous',
            meta_desc: 'Contactez Maison El Wali. Visitez nos showrooms, appelez notre assistance ou envoyez-nous un message.',
            support: 'SUPPORT',
            hero_title_1: 'Entrer en',
            hero_title_2: 'Contact',
            hero_subtitle: 'Nous sommes là pour vous aider à trouver le bijou parfait.',
            visit_flagship: 'Visitez notre Boutique',
            call_support: 'Appeler l\'Assistance',
            email_us: 'Envoyez-nous un Email',
            message_received: 'Message Reçu',
            thanks: 'Merci d\'avoir contacté Maison El Wali. Notre équipe de conciergerie a reçu votre demande.',
            send_another: 'Envoyer un autre message',
            send_message: 'Envoyer un Message',
            name: 'Nom',
            subject: 'Sujet',
            topic_placeholder: 'Sélectionnez un sujet',
            topic_sales: 'Demande de vente',
            topic_support: 'Entretien des Bijoux',
            topic_partnership: 'Partenariat',
            topic_other: 'Autre',
            message: 'Message',
            message_placeholder: 'Comment pouvons-nous vous aider aujourd\'hui ?',
            sending: 'Envoi...',
            send_btn: 'Envoyer le Message',
            hq_name: 'Siège Maison El Wali',
            hq_address: 'Marrakech, Maroc'
        },
        packages: {
            title: 'Forfaits Exclusifs',
            meta_desc: 'Ensembles de bijoux et coffrets cadeaux sélectionnés pour des occasions spéciales.',
            hero_title: 'Forfaits Sélectionnés',
            hero_subtitle: 'Des ensembles exclusifs conçus pour vos moments les plus chers',
            view_details: 'Voir Détails',
            custom_title: 'Forfaits Sur Mesure',
            custom_desc: 'Vous cherchez quelque chose d\'unique ? Nos stylistes peuvent vous conseiller.',
            request: 'Demander une Consultation',
            pkg1_name: 'Ensemble Élégance Nuptiale',
            pkg1_desc: 'Parure de bijoux de mariage complète pour la mariée moderne. Comprend collier, boucles d\'oreilles et bracelet.',
            pkg2_name: 'Collection Anniversaire',
            pkg2_desc: 'Célébrez votre étape importante avec nos favoris d\'anniversaire triés sur le volet. Une bague intemporelle et son pendentif assorti.',
            pkg3_name: 'Luxe au Quotidien',
            pkg3_desc: 'Des pièces subtiles mais époustouflantes conçues pour un usage quotidien. Élevez votre style de tous les jours.',
            pkg4_name: 'Suite Royale de Pierres Précieuses',
            pkg4_desc: 'Une collection majestueuse avec des accents de saphir et de diamant. Digne de la royauté.'
        },
        checkout: {
            title: 'Paiement',
            contact_info: 'Informations de contact',
            shipping_address: 'Adresse de livraison',
            payment_method: 'Mode de paiement',
            email_label: 'Adresse e-mail',
            email_placeholder: 'vous@email.com',
            first_name: 'Prénom',
            last_name: 'Nom',
            address: 'Adresse',
            address_placeholder: '123 Rue Principale',
            city: 'Ville',
            country: 'Pays',
            zip: 'Code postal',
            cod_title: 'Paiement à la livraison',
            cod_desc: 'Payez en espèces à la réception de votre commande',
            place_order: 'Passer la commande',
            processing: 'Traitement...',
            pay: 'Payer',
            order_summary: 'Résumé de la commande',
            shipping: 'Livraison',
            free: 'Gratuit',
            tax: 'Taxe',
            total: 'Total',
            email_error: 'E-mail valide requis',
            required_error: 'Requis',
            failed_order: 'Échec de la commande. Veuillez réessayer.'
        },
        confirmation: {
            title: 'Commande confirmée !',
            subtitle: 'Merci pour votre achat.',
            order_id: 'ID de commande',
            message: 'Nous avons envoyé un e-mail de confirmation à votre boîte de réception. Vous pouvez suivre l\'état de votre commande dans votre compte.',
            continue_shopping: 'Continuer les achats',
            back_home: 'Retour à l\'accueil'
        },
        search: {
            title: 'Résultats de recherche',
            results_for: 'résultats pour',
            placeholder: 'Rechercher des produits, marques, catégories...',
            no_found: 'Aucun produit trouvé',
            no_found_q: 'Essayez d\'autres mots-clés ou parcourez notre catalogue',
            no_found_no_q: 'Entrez un terme de recherche pour trouver des produits',
            browse: 'Parcourir le catalogue'
        },
        pdp: {
            details: 'Détails du produit',
            loading: 'Chargement des détails...',
            not_found: 'Produit non trouvé',
            not_found_desc: 'Le produit que vous recherchez n\'existe pas ou n\'a pas pu être chargé.',
            home: 'Accueil',
            catalog: 'Catalogue',
            reviews: 'avis',
            in_stock: 'En stock',
            out_stock: 'Rupture de stock',
            add_to_cart: 'Ajouter au panier',
            quantity: 'Quantité',
            added_to_cart: 'a été ajouté à votre panier.',
            specs: 'Spécifications',
            related: 'Vous pourriez aussi aimer',
            quick_view: 'Aperçu rapide',
            add_wishlist: 'Ajouter à la liste de souhaits',
            view: 'Voir'
        },
        stores: {
            title: 'Nos emplacements',
            meta_desc: 'Trouvez un showroom près de chez vous. Découvrez nos produits en personne.',
            hero_title: 'Trouvez votre magasin le plus proche',
            hero_subtitle: 'Découvrez nos produits en personne dans l\'un de nos showrooms premium',
            locations: 'Emplacements',
            get_directions: 'Obtenir l\'itinéraire',
            call: 'Appeler le magasin',
            map_title: 'Carte interactive',
            map_desc: 'Connectez l\'API Google Maps pour afficher les emplacements',
            hours: 'Heures d\'ouverture',
            mon_sat: 'Lun-Sam',
            sun: 'Dim',
            expert_staff: 'Personnel expert',
            expert_desc: 'Nos spécialistes formés vous aideront à trouver l\'appareil parfait',
            service_center: 'Centre de service',
            service_desc: 'Réparations en magasin et support technique disponibles',
            experience_person: 'Vivez l\'expérience en personne',
            experience_desc: 'Visitez l\'un de nos showrooms premium pour tester ce produit avant de l\'acheter.'
        }
    },
    ar: {
        nav: {
            catalog: 'المجموعات',
            packages: 'الباقات',
            boutique: 'البوتيك',
            about: 'الدار',
            contact: 'الكونسيرج',
            login: 'تسجيل الدخول',
            admin_portal: 'نظرة عامة على الورشة',
            orders: 'سجل الكنوز',
            products: 'الإبداعات',
            categories: 'تنسيقات',
            brands: 'الحرفيون',
            stores: 'البوتيكات',
            pos: 'المحطة',
            dashboard: 'تحليلات الدار',
            users: 'المستخدمين',
            settings: 'الإعدادات'
        },
        footer: {
            luxury: 'ذهب ومجوهرات فاخرة',
            tagline: 'أناقة خالدة من دبي',
            client_care: 'عناية العملاء',
            book_appt: 'حجز موعد',
            heritage: 'تراثنا',
            rights: 'جميع الحقوق محفوظة.',
            collections: 'المجموعات',
            all_jewelry: 'كل المجوهرات',
            gold_rings: 'خواتم ذهب',
            diamond_necklaces: 'قلادات ألماس',
            luxury_watches: 'ساعات فاخرة',
            bridal_set: 'طقم العروس',
            maison: 'دار ميسون',
            careers: 'وظائف',
            shipping_returns: 'الشحن والإرجاع',
            size_guide: 'دليل المقاسات',
            jewelry_care: 'العناية بالمجوهرات'
        },
        common: {
            search: 'البحث عن المنتجات...',
            search_btn: 'بحث',
            cart: 'السلة',
            language: 'اللغة',
            back_to_store: 'العودة للمتجر',
            logout: 'تسجيل الخروج',
            welcome: 'مرحباً بك',
            explore: 'استكشف المجموعة',
            visit: 'زيارة البوتيك',
            currency: 'درهم',
            email: 'البريد الإلكتروني',
            phone: 'الهاتف',
            total: 'الإجمالي',
            left: 'متبقي',
            try_again: 'إعادة المحاولة',
            go_home: 'الرئيسية',
            error_title: 'حدث خطأ ما',
            error_desc: 'واجهنا خطأ أثناء تحميل هذا المحتوى.',
            admin: 'مسؤول',
            page_not_found: 'الصفحة غير موجودة',
            page_not_found_desc: 'تم نقل الأثر الرقمي الذي تبحث عنه أو أنه غير موجود في هذا البعد.',
            report_issue: 'بلاغ عن مشكلة',
            top_rated: 'الأعلى تقييماً'
        },
        cart: {
            title: 'سلة التسوق',
            empty: 'سلة التسوق فارغة',
            checkout: 'الدفع',
            shipping_hint: 'يتم حساب الشحن والضرائب عند الدفع'
        },
        admin: {
            dashboard: 'تحليلات الدار',
            welcome_back: 'مرحباً بكم في الأتيليه،',
            total_revenue: 'قيمة التراث',
            recent_products: 'أحدث التحف',
            manage_admins: 'إدارة المسؤولين',
            add_product: 'أرشفة إبداع جديد',
            products: 'الإبداعات',
            loading_data: 'جاري تحميل البيانات...',
            failed_load: 'فشل تحميل البيانات',
            retry: 'إعادة المحاولة',
            no_products: 'لا توجد منتجات لعرضها حاليًا',
            product: 'إبداع',
            brand: 'حرفي',
            price: 'السعر',
            stock: 'المخزون',
            rating: 'التقييم',
            actions: 'إجراءات',
            search_placeholder: 'بحث عن المنتجات...',
            delete_confirm: "هل أنت متأكد من حذف '{name}'؟ لا يمكن التراجع عن هذا الإجراء.",
            delete: 'حذف',
            edit: 'تعديل',
            cancel: 'إلغاء',
            save_success: 'تم الحفظ بنجاح',
            delete_success: 'تم الحذف بنجاح',
            save_failed: 'فشل الحفظ',
            low_stock_alerts: 'تنبيهات المخزون المنخفض',
            name: 'الاسم',
            description: 'الوصف',
            select_category: 'اختر الفئة',
            select_brand: 'اختر الماركة',
            image: 'صورة المنتج',
            image_url: 'رابط خارجي',
            upload_image: 'رفع صورة',
            uploading: 'جاري الرفع...',
            update_product: 'تحديث المنتج',
            brands_management: 'إدارة الماركات',
            categories_management: 'إدارة الفئات',
            stores_management: 'إدارة المتاجر',
            add_brand: 'إضافة ماركة',
            add_category: 'إضافة فئة',
            add_store: 'إضافة متجر',
            logo_url: 'رابط الشعار',
            address: 'العنوان',
            city: 'المدينة',
            phone: 'الهاتف',
            orders_management: 'إدارة الطلبات',
            order_id: 'رقم الطلب',
            date: 'التاريخ',
            items: 'العناصر',
            status: 'الحالة',
            completed: 'مكتمل',
            pending: 'قيد الانتظار',
            average_value: 'متوسط قيمة الطلب',
            export_csv: 'تصدير CSV',
            users_management: 'إدارة المستخدمين',
            username: 'اسم المستخدم',
            email: 'البريد الإلكتروني',
            phone_number: 'رقم الهاتف',
            role: 'الصلاحية',
            active: 'نشط',
            inactive: 'غير نشط',
            super_admin: 'مسؤول ممتاز',
            admin: 'مسؤول',
            first_name: 'الاسم الأول',
            last_name: 'الاسم العائلة',
            password: 'كلمة المرور',
            set_as_super_admin: 'تعيين كمسؤول ممتاز',
            store_info: 'معلومات المتجر',
            home_page_content: 'عرض الصفحة الرئيسية',
            theme_customization: 'تخصيص المظهر',
            primary_color: 'لون أساسي',
            secondary_color: 'لون ثانوي',
            accent_color: 'لون التمييز',
            main_font: 'الخط الرئيسي',
            default: 'افتراضي',
            save_changes: 'حفظ التغييرات',
            hero_title_label: 'عنوان البانر الرئيسي (HTML مسموح)',
            hero_subtitle_label: 'العنوان الفرعي',
            hero_badge_label: 'شارة البانر',
            saving: 'جاري الحفظ...',
            admin_login: 'تسجيل دخول المسؤول',
            backend_online: 'الخادم متصل',
            backend_offline: 'الخادم غير متصل',
            confirm_dialog: {
                default_title: 'هل أنت متأكد؟',
                default_message: 'لا يمكن التراجع عن هذا الإجراء.',
                confirm: 'تأكيد',
                cancel: 'إلغاء'
            },
            checking_connectivity: 'جاري التحقق من الاتصال...',
            sign_in_subtitle: 'سجل الدخول للوصول إلى لوحة التحكم',
            forgot_password: 'نسيت كلمة المرور؟',
            signing_in: 'جاري تسجيل الدخول...',
            sign_in: 'تسجيل الدخول',
            invalid_credentials: 'اسم المستخدم أو كلمة المرور غير صالحة',
            weekly_sales: 'المبيعات الأسبوعية',
            healthy_stock: 'جميع المخزونات سليمة! ✅',
            sales: 'المبيعات',
            dashboard_overview: 'نظرة عامة على لوحة التحكم',
            customer: 'العميل',
            guest: 'زائر',
            payment: 'الدفع',
            view_details: 'عرض التفاصيل',
            print_receipt: 'طباعة الإيصال',
            add_admin: 'إضافة مسؤول',
            quick_actions: 'إجراءات سريعة',
            edit_categories: 'تعديل الفئات',
            edit_brands: 'تعديل الماركات'
        },
        wishlist: {
            title: 'قائمة الأمنيات',
            empty_title: 'قائمة الأمنيات فارغة',
            empty_desc: 'لم تقم بإضافة أي كنوز إلى مجموعتك بعد.',
            browse: 'تصفح المنتجات',
            added_success: 'تمت الإضافة إلى مجموعتك الخاصة.',
            removed_success: 'تمت الإزالة من مجموعتك الخاصة.',
            add_failed: 'فشل الإضافة إلى قائمة الأمنيات.',
            remove_failed: 'فشل الإزالة من قائمة الأمنيات.'
        },
        account: {
            welcome: 'مرحباً،',
            dashboard_desc: 'إدارة مجموعتك التراثية وكنوزك الثمينة.',
            total_orders: 'إجمالي المقتنيات',
            recent_orders: 'التراث الأخير',
            view_all: 'عرض السجل الكامل',
            no_orders: 'لا توجد طلبات حتى الآن.',
            order_history: 'سجل الطلبات',
            loading: 'جاري التحميل...',
            order_id: 'رقم الطلب',
            date: 'التاريخ',
            status: 'الحالة',
            total: 'الإجمالي',
            no_previous_orders: 'لا توجد طلبات سابقة.',
            shop_now: 'تسوق الآن',
            account_settings: 'إعدادات الحساب',
            first_name: 'الاسم الأول',
            last_name: 'اسم العائلة',
            save_success: 'تم تحديث البيانات بنجاح',
            save_failed: 'حدث خطأ أثناء التحديث',
            saving: 'جاري الحفظ...',
            save_changes: 'حفظ التغييرات',
            my_account: 'حسابي',
            logout: 'تسجيل الخروج'
        },
        pos: {
            title: 'محطة الحرفي',
            back_to_admin: 'العودة إلى المسؤول',
            current_order: 'الطلب الحالي',
            clear_all: 'مسح الكل',
            cart_empty: 'السلة فارغة',
            add_hint: 'انقر على المنتجات لإضافتها',
            subtotal: 'المجموع الفرعي',
            tax: 'الضريبة',
            total: 'الإجمالي',
            processing: 'جاري المعالجة...',
            order_placed: 'تم تقديم الطلب!',
            complete_order: 'إكمال الطلب',
            order_error: 'خطأ في تقديم الطلب'
        },
        about: {
            title: 'من نحن',
            hero_title: 'فن الفخامة الخالدة',
            hero_subtitle: 'وجهتك الأولى للمجوهرات الحصرية وإبداعات الذهب الرائعة.',
            mission_title: 'مهمتنا',
            mission_desc: 'نحن نؤمن بأن المجوهرات يجب أن تكون أكثر من مجرد زينة - يجب أن تكون إرثاً. في Maison El Wali، نسد الفجوة بين التصميم المميز والبراعة الحرفية.',
            premium_brands: 'ماركات فاخرة',
            global_showrooms: 'صالات عرض عالمية',
            expert_support: 'دعم الخبراء',
            why_choose_us: 'لماذا تختارنا',
            standards_desc: 'المعايير التي تحدد مجموعتنا',
            curated_excellence: 'تميز مختار',
            curated_desc: 'يتم اختيار كل قطعة يدوياً للحرفية المتفوقة والتصميم والقيمة الأبدية.',
            innovation_first: 'تراث حرفي',
            innovation_desc: 'احصل على مجموعات المجوهرات الراقية الحصرية المصنوعة يدوياً من قبل كبار صائغي الذهب لدينا.',
            premium_guarantee: 'ضمان متميز',
            guarantee_desc: 'تغطية ضمان شاملة ودعم كونسيرج مخصص لكل عملية شراء.',
            ready_to_experience: 'هل أنت مستعد للتجربة؟',
            cta_desc: 'قم بزيارة صالة العرض الرقمية الخاصة بنا أو ابحث عن موقع قريب منك.',
            browse_collection: 'تصفح المجموعة',
            find_store: 'ابحث عن متجر'
        },
        home: {
            title: 'الرئيسية',
            meta_desc: 'ميزون الوالي - قمة الفخامة في الذهب والمجوهرات. اكتشف مجموعاتنا الحصرية.',
            luxury_authentic: 'فخامة أصيلة',
            luxury_desc: 'كل قطعة معتمدة ومصنوعة من أنقى أنواع الذهب.',
            global_shipping: 'شحن عالمي',
            shipping_desc: 'توصيل آمن ومؤمن إلى باب منزلك، في أي مكان في العالم.',
            bespoke_design: 'تصميم خاص',
            bespoke_desc: 'تعاون مع حرفيينا لتجسيد رؤيتك الفريدة.',
            gold_standard: 'معيار الذهب',
            teaser_desc: 'من دبي إلى العالم، نقدم لك مجوهرات تتجاوز الأجيال.',
            read_story: 'اقرأ قصتنا'
        },
        catalog: {
            title: 'كتالوج المنتجات',
            quick_actions: 'إجراءات سريعة',
            edit_categories: 'تعديل الفئات',
            edit_brands: 'تعديل الماركات',
            loading: 'جاري تحميل المنتجات...',
            failed: 'فشل تحميل المنتجات',
            error_desc: 'تعذر تحميل كتالوج المنتجات. يرجى التحقق من الاتصال والمحاولة مرة أخرى.',
            filters: 'الفلاتر',
            clear_all: 'مسح الكل',
            categories: 'الفئات',
            brands: 'الماركات',
            search_placeholder: 'بحث عن المنتجات...',
            count_plural: 'منتج',
            sort_featured: 'المميز',
            sort_price_low: 'السعر: من الأقل للأعلى',
            sort_price_high: 'السعر: من الأعلى للأقل',
            sort_rating: 'الأعلى تقييماً',
            no_found: 'لم يتم العثور على منتجات',
            no_found_desc: 'حاول تعديل البحث أو الفلاتر'
        },
        boutique: {
            title: 'البوتيك الرئيسي',
            meta_desc: 'تفضل بزيارة بوتيكنا الرئيسي في دبي. جرب الخدمة الفاخرة ومجموعات المجوهرات الحصرية.',
            experience: 'التجربة',
            hero_title: 'بوتيكنا الرئيسي',
            hero_subtitle: 'انغمس في عالم من الفخامة الراقية في صالة عرضنا بدبي.',
            visit_us: 'تفضل بزيارتنا',
            get_directions: 'الحصول على الاتجاهات',
            call: 'اتصل بالبوتيك',
            hours: 'ساعات العمل',
            mon_fri: 'الأثنين - الجمعة',
            sat_sun: 'السبت - الأحد',
            appointments: 'مواعيد خاصة',
            appointments_desc: 'للحصول على تجربة شخصية، احجز موعداً خاصاً مع كبار مستشاري المجوهرات لدينا.',
            book: 'حجز موعد',
            map_view: 'عرض الخريطة',
            services: 'خدمات البوتيك',
            custom_design: 'تصميم مخصص',
            custom_desc: 'اعمل مع حرفيينا لإنشاء قطعة فريدة من نوعها.',
            spa: 'سبا المجوهرات',
            spa_desc: 'تنظيف وترميم احترافي لقطعك الثمينة.',
            vip: 'صالة VIP',
            vip_desc: 'استمتع بالمرطبات في أجنحة العرض الخاصة بنا.'
        },
        contact: {
            title: 'اتصل بنا',
            meta_desc: 'تواصل مع Maison El Wali. تفضل بزيارة صالات عرضنا، أو اتصل بخط الدعم، أو أرسل لنا رسالة.',
            support: 'الدعم',
            hero_title_1: 'ابق على',
            hero_title_2: 'تواصل',
            hero_subtitle: 'نحن هنا لمساعدتكم في العثور على القطعة المثالية.',
            visit_flagship: 'قم بزيارة بوتيكنا',
            call_support: 'اتصل بالدعم',
            email_us: 'أرسل لنا بريداً إلكترونياً',
            message_received: 'تم استلام الرسالة',
            thanks: 'شكراً لتواصلك مع Maison El Wali. استلم فريق الكونسيرج استفسارك وسيرد عليك قريباً.',
            send_another: 'إرسال رسالة أخرى',
            send_message: 'أرسل رسالة',
            name: 'الاسم',
            subject: 'الموضوع',
            topic_placeholder: 'اختر موضوعاً',
            topic_sales: 'استفسار عن المبيعات',
            topic_support: 'صيانة المجوهرات',
            topic_partnership: 'شراكة',
            topic_other: 'أخرى',
            message: 'الرسالة',
            message_placeholder: 'كيف يمكننا مساعدتك اليوم؟',
            sending: 'جاري الإرسال...',
            send_btn: 'إرسال الرسالة',
            hq_name: 'المقر الرئيسي لميزون الوالي',
            hq_address: 'مراكش، المغرب'
        },
        packages: {
            title: 'باقات حصرية',
            meta_desc: 'باقات مجوهرات ومجموعات هدايا مختارة للمناسبات الخاصة.',
            hero_title: 'باقات مختارة',
            hero_subtitle: 'مجموعات حصرية مصممة لأغلى لحظاتك',
            view_details: 'عرض التفاصيل',
            custom_desc: 'هل تبحث عن شيء فريد؟ يمكن لمصممينا تقديم استشارة.',
            request: 'طلب استشارة',
            pkg1_name: 'طقم أناقة العروس',
            pkg1_desc: 'طقم مجوهرات يوم الزفاف الكامل المصمم للعروس العصرية. يتضمن قلادة وأقراط وسواراً.',
            pkg2_name: 'مجموعة الذكرى السنوية',
            pkg2_desc: 'احتفل بذكرى محطتك الهامة مع قطعنا المختارة للذكرى السنوية. خاتم خالد وقلادة مطابقة.',
            pkg3_name: 'فخامة يومية',
            pkg3_desc: 'قطع ناعمة ولكن مذهلة مصممة للارتداء اليومي. ارفع من أسلوبك اليومي.',
            pkg4_name: 'جناح الأحجار الكريمة الملكي',
            pkg4_desc: 'مجموعة مهيبة تتميز بلمسات من الياقوت والألماس. تليق بالملوك.'
        },
        checkout: {
            title: 'الدفع',
            contact_info: 'معلومات الاتصال',
            shipping_address: 'عنوان الشحن',
            payment_method: 'طريقة الدفع',
            email_label: 'البريد الإلكتروني',
            email_placeholder: 'you@email.com',
            first_name: 'الاسم الأول',
            last_name: 'الاسم الأخير',
            address: 'العنوان',
            address_placeholder: 'شارع رقم 123',
            city: 'المدينة',
            country: 'البلد',
            zip: 'الرمز البريدي',
            cod_title: 'الدفع عند الاستلام',
            cod_desc: 'ادفع نقداً عند استلام طلبك',
            place_order: 'إتمام الطلب',
            processing: 'جاري المعالجة...',
            pay: 'دفع',
            order_summary: 'ملخص الطلب',
            shipping: 'الشحن',
            free: 'مجاني',
            tax: 'الضريبة',
            total: 'الإجمالي',
            email_error: 'يرجى إدخال بريد إلكتروني صالح',
            required_error: 'مطلوب',
            failed_order: 'فشل إتمام الطلب. يرجى المحاولة مرة أخرى.'
        },
        confirmation: {
            title: 'تم تأكيد الطلب!',
            subtitle: 'شكراً لك على شرائك.',
            order_id: 'رقم الطلب',
            message: 'لقد أرسلنا رسالة تأكيد إلكترونية إلى بريدك الوظارد. يمكنك تتبع حالة طلبك في حسابك.',
            continue_shopping: 'مواصلة التسوق',
            back_home: 'العودة للرئيسية'
        },
        search: {
            title: 'نتائج البحث',
            results_for: 'نتائج لـ',
            placeholder: 'بحث عن منتجات، ماركات، فئات...',
            no_found: 'لم يتم العثور على منتجات',
            no_found_q: 'جرب كلمات أخرى أو تصفح مجموعتنا',
            no_found_no_q: 'أدخل كلمة للبحث عن منتجات',
            browse: 'تصفح الكتالوج'
        },
        pdp: {
            details: 'تفاصيل المنتج',
            loading: 'جاري تحميل التفاصيل...',
            not_found: 'المنتج غير موجود',
            not_found_desc: 'المنتج الذي تبحث عنه غير موجود أو تعذر تحميله.',
            home: 'الرئيسية',
            catalog: 'الكتالوج',
            reviews: 'مراجعات',
            in_stock: 'متوفر',
            out_stock: 'نفذ من المخزون',
            add_to_cart: 'أضف للسلة',
            quantity: 'الكمية',
            added_to_cart: 'تمت إضافته إلى السلة بنجاح.',
            specs: 'المواصفات',
            related: 'قد يعجبك أيضاً',
            quick_view: 'عرض سريع',
            add_wishlist: 'أضف لقائمة الأمنيات',
            view: 'عرض'
        },
        stores: {
            title: 'مواقعنا',
            meta_desc: 'ابحث عن أقرب معرض لك. جرب منتجاتنا بنفسك.',
            hero_title: 'ابحث عن أقرب متجر',
            hero_subtitle: 'جرب منتجاتنا بنفسك في أحد صالات عرضنا المتميزة',
            locations: 'المواقع',
            get_directions: 'الحصول على الاتجاهات',
            call: 'اتصل بالمتجر',
            map_title: 'خريطة تفاعلية',
            map_desc: 'قم بربط خرائط جوجل لعرض المواقع',
            hours: 'ساعات العمل',
            mon_sat: 'الاثنين - السبت',
            sun: 'الأحد',
            expert_staff: 'فريق عمل خبير',
            expert_desc: 'سيساعدك المتخصصون لدينا في العثور على القطعة المثالية',
            service_center: 'ورشة الحرفيين',
            service_desc: 'تتوفر خدمات تغيير الحجم والصيانة المهنية في المتجر',
            experience_person: 'جربها بنفسك',
            experience_desc: 'قم بزيارة أحد صالات عرضنا لتجربة هذه القطعة قبل الشراء.'
        }
    }
}

export const useLanguage = () => {
    const translateLanguage = (path: string) => {
        const keys = path.split('.')
        let result: any = translations[currentLocale.value]
        for (const key of keys) {
            if (result[key]) {
                result = result[key]
            } else {
                return path
            }
        }
        return result
    }

    const setLocale = (locale: Locale) => {
        currentLocale.value = locale
        if (process.client) {
            localStorage.setItem('locale', locale)
            updateDirection()
        }
    }

    const updateDirection = () => {
        if (process.client) {
            const dir = currentLocale.value === 'ar' ? 'rtl' : 'ltr'
            document.documentElement.setAttribute('dir', dir)
            document.documentElement.setAttribute('lang', currentLocale.value)
        }
    }

    const initLocale = () => {
        if (process.client) {
            const saved = localStorage.getItem('locale') as Locale
            if (saved && ['en', 'fr', 'ar'].includes(saved)) {
                currentLocale.value = saved
            }
            updateDirection()
        }
    }

    onMounted(initLocale)

    return {
        locale: readonly(currentLocale),
        translateLanguage,
        setLocale,
        isRtl: computed(() => currentLocale.value === 'ar')
    }
}
